fix(core): make model and resposiory customizable
sourcefuse/loopback4-audit-log pull request #124
Opened 2024-06-13 11:49 UTC by yeshamavani

now user can use the default as well as their custom respository

GH-121

## Description

The mixin now accepts two optional parameters for audit model and repository

Fixes #121

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

Created a sample app and tested that

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2024-07-01 12:58 UTC, samarpan-b requested changes
Why are we doing this ? Who requested ?

2024-07-01 15:19 UTC, yeshamavani commented
> Why are we doing this ? Who requested ?

This is in respect to the issue raised by community 
https://github.com/sourcefuse/loopback4-audit-log/issues/121

2024-11-06 11:27 UTC, mrbatista commented
@yeshamavani Any update on this PR?

2024-11-06 12:50 UTC, yeshamavani commented
> @yeshamavani Any update on this PR?

This PR is under review I will update you once we release this soon 
Feel free to review this PR and open for suggestions

2025-04-16 08:30 UTC, mrbatista commented
@yeshamavani any news?

2025-04-17 07:59 UTC, samarpan-b reviewed
I have one query. Isnt this going to break existing consumers of this package ?

2025-04-21 04:11 UTC, merged

2025-04-21 13:37 UTC, yeshamavani commented
:tada: This PR is included in version 8.0.6 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@sourceloop/audit-log/v/8.0.6)
- [GitHub release](https://github.com/sourcefuse/loopback4-audit-log/releases/tag/v8.0.6)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: