added audit creation optional flag
sourcefuse/loopback4-audit-log pull request #2
Opened 2021-03-16 13:50 UTC by mlakdawala-sf

2021-03-16 17:04 UTC, samarpan-b requested changes

2021-03-16 17:04 UTC, samarpan-b commented on src/types.ts
> +  noAuditCreation: boolean;
Not needed. Just dont use this mixin wherever you dont want audit.

2021-03-17 09:07 UTC, samarpan-b requested changes

2021-03-17 09:07 UTC, samarpan-b commented on src/types.ts
> +interface AuditLogOption {
export this interface as well

2021-03-17 09:11 UTC, mlakdawala-sf commented on src/types.ts
> +interface AuditLogOption {
done

2021-03-17 09:14 UTC, samarpan-b approved these changes

2021-03-17 09:14 UTC, samarpan-b commented
Please update readme

2021-03-17 09:54 UTC, samarpan-b approved these changes

2021-03-17 09:54 UTC, merged